name: spiral_journal
description: A beautiful journaling app with emotional intelligence tracking

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  
  # Production Backend Dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4
  
  # AI & HTTP Client
  http: ^1.1.0
  dio: ^5.4.0
  
  # Data Security & Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # State Management & Utils
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
